//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public Accounts()
        {
            this.CustomerPosting = new HashSet<CustomerPosting>();
            this.CustomerPosting1 = new HashSet<CustomerPosting>();
            this.ItemPosting = new HashSet<ItemPosting>();
            this.ItemPosting1 = new HashSet<ItemPosting>();
            this.ItemPosting2 = new HashSet<ItemPosting>();
            this.ItemPosting3 = new HashSet<ItemPosting>();
            this.ItemPosting4 = new HashSet<ItemPosting>();
            this.ItemPosting5 = new HashSet<ItemPosting>();
            this.ItemPosting6 = new HashSet<ItemPosting>();
            this.ItemPosting7 = new HashSet<ItemPosting>();
            this.ItemPosting8 = new HashSet<ItemPosting>();
            this.StructureDeminsions = new HashSet<StructureDeminsions>();
            this.VendorPosting = new HashSet<VendorPosting>();
            this.VendorPosting1 = new HashSet<VendorPosting>();
        }
    
        public string accCode { get; set; }
        public string accName { get; set; }
        public Nullable<int> accLevel { get; set; }
        public string MainAccCode { get; set; }
        public Nullable<int> typeCode { get; set; }
        public Nullable<bool> AllowManualEntry { get; set; }
    
        public virtual AccountBalance AccountBalance { get; set; }
        public virtual AccountType AccountType { get; set; }
        public virtual ICollection<CustomerPosting> CustomerPosting { get; set; }
        public virtual ICollection<CustomerPosting> CustomerPosting1 { get; set; }
        public virtual ICollection<ItemPosting> ItemPosting { get; set; }
        public virtual ICollection<ItemPosting> ItemPosting1 { get; set; }
        public virtual ICollection<ItemPosting> ItemPosting2 { get; set; }
        public virtual ICollection<ItemPosting> ItemPosting3 { get; set; }
        public virtual ICollection<ItemPosting> ItemPosting4 { get; set; }
        public virtual ICollection<ItemPosting> ItemPosting5 { get; set; }
        public virtual ICollection<ItemPosting> ItemPosting6 { get; set; }
        public virtual ICollection<ItemPosting> ItemPosting7 { get; set; }
        public virtual ICollection<ItemPosting> ItemPosting8 { get; set; }
        public virtual ICollection<StructureDeminsions> StructureDeminsions { get; set; }
        public virtual ICollection<VendorPosting> VendorPosting { get; set; }
        public virtual ICollection<VendorPosting> VendorPosting1 { get; set; }
    }
}
