//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMHeader
    {
        public BOMHeader()
        {
            this.BOMIngredientsProducts = new HashSet<BOMIngredientsProducts>();
            this.BOMOutputProduct = new HashSet<BOMOutputProduct>();
        }
    
        public long BOMCode { get; set; }
        public string BOMLookUpCode { get; set; }
        public Nullable<System.DateTime> BOMDate { get; set; }
        public Nullable<int> JournalCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserCode { get; set; }
        public Nullable<bool> IsPosted { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<BOMIngredientsProducts> BOMIngredientsProducts { get; set; }
        public virtual ICollection<BOMOutputProduct> BOMOutputProduct { get; set; }
    }
}
