//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Site = new HashSet<Site>();
            this.Customer = new HashSet<Customer>();
            this.Employee = new HashSet<Employee>();
            this.Organization = new HashSet<Organization>();
            this.Vendor = new HashSet<Vendor>();
        }
    
        public int City_Code { get; set; }
        public string City_Name { get; set; }
        public Nullable<int> Country_Code { get; set; }
    
        public virtual ICollection<Site> Site { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<Organization> Organization { get; set; }
        public virtual ICollection<Vendor> Vendor { get; set; }
    }
}
