//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.SalesHeader = new HashSet<SalesHeader>();
        }
    
        public int Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> City_Code { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string EMail { get; set; }
        public string FaceBook { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> GroupCode { get; set; }
    
        public virtual City City { get; set; }
        public virtual CustomerGroup CustomerGroup { get; set; }
        public virtual ICollection<SalesHeader> SalesHeader { get; set; }
    }
}
