//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGroup
    {
        public CustomerGroup()
        {
            this.Customer = new HashSet<Customer>();
        }
    
        public int GroupCode { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual CustomerPosting CustomerPosting { get; set; }
    }
}
