//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.User = new HashSet<User>();
            this.WareHouse = new HashSet<WareHouse>();
        }
    
        public int Employee_Code { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<int> Manager_Code { get; set; }
        public Nullable<int> Job_Code { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public byte[] Employee_Image { get; set; }
        public string Address { get; set; }
        public Nullable<int> City_Code { get; set; }
        public string Email { get; set; }
        public string LinkedIn { get; set; }
        public string FaceBook { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public Nullable<int> MaritalStatus_Code { get; set; }
        public Nullable<decimal> FixedSalary { get; set; }
        public Nullable<decimal> MotivateSalary { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public Nullable<long> FinDemCode { get; set; }
    
        public virtual City City { get; set; }
        public virtual FinancialDeminsions FinancialDeminsions { get; set; }
        public virtual Job Job { get; set; }
        public virtual MaritalStatus MaritalStatus { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<WareHouse> WareHouse { get; set; }
    }
}
