//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expired_Date
    {
        public int Expired_Code { get; set; }
        public Nullable<System.DateTime> Expired_Date1 { get; set; }
        public Nullable<int> Product_Code { get; set; }
        public Nullable<int> Inventory_Code { get; set; }
        public Nullable<decimal> Qty { get; set; }
    
        public virtual WareHouse WareHouse { get; set; }
        public virtual Product Product { get; set; }
    }
}
