//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialCategory
    {
        public FinancialCategory()
        {
            this.FinancialDeminsions = new HashSet<FinancialDeminsions>();
            this.StructureDeminsions = new HashSet<StructureDeminsions>();
        }
    
        public int FinCatCode { get; set; }
        public string FinCatName { get; set; }
    
        public virtual ICollection<FinancialDeminsions> FinancialDeminsions { get; set; }
        public virtual ICollection<StructureDeminsions> StructureDeminsions { get; set; }
    }
}
