//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialDeminsions
    {
        public FinancialDeminsions()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public long FinDemCode { get; set; }
        public string FinDemName { get; set; }
        public Nullable<int> FinCatCode { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual FinancialCategory FinancialCategory { get; set; }
    }
}
