//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPosting
    {
        public int ProductGroupCode { get; set; }
        public string IssueAccount { get; set; }
        public string ConsumptionAccount { get; set; }
        public string RevenueAccount { get; set; }
        public string SalesDiscountAccount { get; set; }
        public string SalesTaxesAccount { get; set; }
        public string ProductRecieptAccount { get; set; }
        public string PurchaseAccrualAccount { get; set; }
        public string PurchaseDiscountAccount { get; set; }
        public string PurchaseTaxesAccount { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Accounts Accounts1 { get; set; }
        public virtual Accounts Accounts2 { get; set; }
        public virtual Accounts Accounts3 { get; set; }
        public virtual Accounts Accounts4 { get; set; }
        public virtual Accounts Accounts5 { get; set; }
        public virtual Accounts Accounts6 { get; set; }
        public virtual Accounts Accounts7 { get; set; }
        public virtual Accounts Accounts8 { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
    }
}
