//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OK_DBEntities : DbContext
    {
        //public OK_DBEntities()
        //    : base("name=OK_DBEntities")
        //{
        //}
        private class Inner
        {
            public static OK_DBEntities OK_DBEntities;
            static Inner()
            {
                OK_DBEntities = new OK_DBEntities();
            }
        }
        public static OK_DBEntities OK_DBEntitiesInstatnce
        {
            get
            {
                return Inner.OK_DBEntities;
            }
        }
        private OK_DBEntities()
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountBalance> AccountBalance { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<AccountStructure> AccountStructure { get; set; }
        public virtual DbSet<AccountType> AccountType { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroup { get; set; }
        public virtual DbSet<CustomerPosting> CustomerPosting { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Expired_Date> Expired_Date { get; set; }
        public virtual DbSet<FinancialCategory> FinancialCategory { get; set; }
        public virtual DbSet<FinancialDeminsions> FinancialDeminsions { get; set; }
        public virtual DbSet<ItemPosting> ItemPosting { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JournalNames> JournalNames { get; set; }
        public virtual DbSet<Lic> Lic { get; set; }
        public virtual DbSet<MaritalStatus> MaritalStatus { get; set; }
        public virtual DbSet<OfferedProducts> OfferedProducts { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<PermissionsInScreen> PermissionsInScreen { get; set; }
        public virtual DbSet<PostedTransactions> PostedTransactions { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductGroup> ProductGroup { get; set; }
        public virtual DbSet<ProductOffers> ProductOffers { get; set; }
        public virtual DbSet<ProductOnHand> ProductOnHand { get; set; }
        public virtual DbSet<PurchaseDetails> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseHeader> PurchaseHeader { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SalesDetails> SalesDetails { get; set; }
        public virtual DbSet<SalesHeader> SalesHeader { get; set; }
        public virtual DbSet<Screen> Screen { get; set; }
        public virtual DbSet<ScreensInRole> ScreensInRole { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<StructureDeminsions> StructureDeminsions { get; set; }
        public virtual DbSet<TransactionHeader> TransactionHeader { get; set; }
        public virtual DbSet<TransactionLines> TransactionLines { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<UOMCCategory> UOMCCategory { get; set; }
        public virtual DbSet<UOMConversions> UOMConversions { get; set; }
        public virtual DbSet<UOMCType> UOMCType { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<VendorGroup> VendorGroup { get; set; }
        public virtual DbSet<VendorPosting> VendorPosting { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
        public virtual DbSet<BOMHeader> BOMHeader { get; set; }
        public virtual DbSet<BOMIngredientsProducts> BOMIngredientsProducts { get; set; }
        public virtual DbSet<BOMOutputProduct> BOMOutputProduct { get; set; }
    }
}
