//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        public string Address { get; set; }
        public Nullable<int> City_Code { get; set; }
        public byte[] Logo { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string EMail { get; set; }
    
        public virtual City City { get; set; }
    }
}
