//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionsInScreen
    {
        public long ID { get; set; }
        public Nullable<int> Screen_Code { get; set; }
        public Nullable<int> Permission_Code { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual Screen Screen { get; set; }
    }
}
