//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostedTransactions
    {
        public long LinCode { get; set; }
        public Nullable<long> transCode { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.TimeSpan> PostedTime { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string accCode { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
    
        public virtual TransactionHeader TransactionHeader { get; set; }
        public virtual User User { get; set; }
    }
}
