//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOnHand
    {
        public long ID { get; set; }
        public Nullable<int> Product_Code { get; set; }
        public Nullable<int> WHCode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<int> Unit_Code { get; set; }
        public Nullable<decimal> LastPurchasePrice { get; set; }
        public Nullable<decimal> NewPurchasePrice { get; set; }
        public Nullable<decimal> AvgCost { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
