//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroup
    {
        public ProductGroup()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int GroupCode { get; set; }
        public string GroupName { get; set; }
    
        public virtual ItemPosting ItemPosting { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
