//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOffers
    {
        public ProductOffers()
        {
            this.OfferedProducts = new HashSet<OfferedProducts>();
        }
    
        public int OfferCode { get; set; }
        public Nullable<decimal> OfferPrice { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<OfferedProducts> OfferedProducts { get; set; }
    }
}
