//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetails
    {
        public long ID { get; set; }
        public string Purchase_Code { get; set; }
        public Nullable<int> Product_Code { get; set; }
        public Nullable<int> Unit_Code { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Expired_Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchaseHeader PurchaseHeader { get; set; }
    }
}
