//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHeader
    {
        public PurchaseHeader()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetails>();
        }
    
        public string Purchase_Code { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<System.TimeSpan> Purchase_Time { get; set; }
        public Nullable<decimal> Purchase_Total { get; set; }
        public Nullable<decimal> Purchase_Paied { get; set; }
        public Nullable<decimal> Purchase_Reminder { get; set; }
        public Nullable<bool> Type_Code { get; set; }
        public Nullable<int> Inventory_Code { get; set; }
        public Nullable<int> Vendor_Code { get; set; }
        public Nullable<int> User_Code { get; set; }
        public Nullable<bool> PaymentSystem { get; set; }
    
        public virtual ICollection<PurchaseDetails> PurchaseDetails { get; set; }
        public virtual User User { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
