//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHeader
    {
        public SalesHeader()
        {
            this.SalesDetails = new HashSet<SalesDetails>();
        }
    
        public string Sales_Code { get; set; }
        public Nullable<System.DateTime> Sales_Date { get; set; }
        public Nullable<System.TimeSpan> Sales_Time { get; set; }
        public Nullable<decimal> Sales_Total { get; set; }
        public Nullable<decimal> Sales_Paied { get; set; }
        public Nullable<decimal> Sales_Reminder { get; set; }
        public Nullable<bool> Type_Code { get; set; }
        public Nullable<int> Inventory_Code { get; set; }
        public Nullable<int> Customer_Code { get; set; }
        public Nullable<int> User_Code { get; set; }
        public Nullable<bool> PaymentSystem { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SalesDetails> SalesDetails { get; set; }
        public virtual User User { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
