//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.WareHouse = new HashSet<WareHouse>();
        }
    
        public int Site_Code { get; set; }
        public string Site_Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> City_Code { get; set; }
        public string Site_Type { get; set; }
        public string Notes { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<WareHouse> WareHouse { get; set; }
    }
}
