//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        public WareHouse()
        {
            this.Expired_Date = new HashSet<Expired_Date>();
            this.Product = new HashSet<Product>();
            this.Product1 = new HashSet<Product>();
            this.ProductOnHand = new HashSet<ProductOnHand>();
            this.PurchaseHeader = new HashSet<PurchaseHeader>();
            this.SalesHeader = new HashSet<SalesHeader>();
            this.BOMIngredientsProducts = new HashSet<BOMIngredientsProducts>();
            this.BOMOutputProduct = new HashSet<BOMOutputProduct>();
        }
    
        public int WareHouse_Code { get; set; }
        public string WareHouse_Name { get; set; }
        public Nullable<int> Site_Code { get; set; }
        public string WareHouse_Type { get; set; }
        public Nullable<int> ManagerCode { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Expired_Date> Expired_Date { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Product> Product1 { get; set; }
        public virtual ICollection<ProductOnHand> ProductOnHand { get; set; }
        public virtual ICollection<PurchaseHeader> PurchaseHeader { get; set; }
        public virtual ICollection<SalesHeader> SalesHeader { get; set; }
        public virtual Site Site { get; set; }
        public virtual ICollection<BOMIngredientsProducts> BOMIngredientsProducts { get; set; }
        public virtual ICollection<BOMOutputProduct> BOMOutputProduct { get; set; }
    }
}
